import Header from "@/components/Header";
import Providers from "./Providers";
import "./globals.css";
import Footer from "@/components/Footer";


export const metadata = {
  title: "Islandcosa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
        <Header/>
          <div className="">{children}</div>
          <Footer/>
        </Providers>
      </body>
    </html>
  );
}
